#pragma once

//defines argument settings

#include <filesystem>

namespace PPC::Analyse::Arguments
{
	//defines the argument settings
	struct ArgumentSettings
	{
		bool generateTypeNames = true, //the names should be renamed to show the types
			isPretty = false, //the outputted data should be more human readable
			splitIntoOwnFiles = true; //should the functions, structs, and syms be outputted into their own files

		std::filesystem::path DTK_asmDir = "", //the assembly generated by DTK
			DTK_splitsNSymbolsDir = "", //the directory where the symbols and splits were outputed by DTK

			PPC_symbolMapDir = "", //the directory where the PPC Symbol Map will be outputed
			PPC_tokenizedASMFilesDir = ""; //the directory where the PPC ASM Tokenized files will be outputed or located
	};
}